/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import regraNegocio.BebidaRN;
import vo.BebidaVO;

/**
 *
 * @author Raphael
 */
public class Bebida extends Template implements ActionListener{

    /**
     * Creates new form Bebida
     */
    public Bebida() {
        initComponents();
        listarBebida();
        popularMarca();
        popularTipo();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtVolume = new javax.swing.JTextField();
        cbVolume = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cbTipo = new javax.swing.JComboBox<>();
        btTipo = new javax.swing.JButton();
        txtPreco = new javax.swing.JTextField();
        cbMarca = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btMarca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bebida");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Volume :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtVolume.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVolume.setEnabled(false);

        cbVolume.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbVolume.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "ml" }));
        cbVolume.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cbVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cbTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTipo.setEnabled(false);
        cbTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoMouseClicked(evt);
            }
        });
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        btTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_add.png"))); // NOI18N
        btTipo.setToolTipText("Pode se cadastrar novos tipos de bebidas!");
        btTipo.setEnabled(false);
        btTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btTipo)
        );

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPreco.setEnabled(false);

        cbMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbMarca.setEnabled(false);
        cbMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMarcaMouseClicked(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Código :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Marca :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Preço :");

        btMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_add.png"))); // NOI18N
        btMarca.setToolTipText("Pode se cadastrar novas marcas!");
        btMarca.setEnabled(false);
        btMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addComponent(btMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    public void btCadastrarActionPerformed(ActionEvent e) {                                            
        txtPreco.setEnabled(true);
        txtVolume.setEnabled(true);
        cbMarca.setEnabled(true);
        cbTipo.setEnabled(true);
        cbVolume.setEnabled(true);
        btTipo.setEnabled(true);
        btMarca.setEnabled(true);
        
        BebidaRN bebidaRN = new BebidaRN();        
        try {
            int ultimoID = bebidaRN.pegarUltimoID() + 1;
            txtCodigo.setText(String.valueOf(ultimoID));
        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Borda", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Borda", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    @Override
    public void btEditarActionPerformed(ActionEvent e) {
        txtPreco.setEnabled(true);
        txtVolume.setEnabled(true);
        cbMarca.setEnabled(true);
        cbTipo.setEnabled(true);
        cbVolume.setEnabled(true);
        btTipo.setEnabled(true);
        btMarca.setEnabled(true);
       
        
        int selecionada = tbTemplate.getSelectedRow();
        String vtemp = ((String) tbTemplate.getValueAt(selecionada,4));
            txtCodigo.setText((tbTemplate.getValueAt(selecionada, 0).toString()));
            cbMarca.setSelectedItem(tbTemplate.getValueAt(selecionada,2));
            cbTipo.setSelectedItem(tbTemplate.getValueAt(selecionada,3));
            txtPreco.setText(vtemp.replace(" ", "").replace("R","").replace("$","").replace(",","."));
            cbVolume.setSelectedItem(tbTemplate.getValueAt(selecionada,5));
            txtVolume.setText((tbTemplate.getValueAt(selecionada, 6).toString()));  
    }

    @Override
    public void btExcluirActionPerformed(ActionEvent e) {
        txtPreco.setEnabled(false);
        txtVolume.setEnabled(false);
        cbMarca.setEnabled(false);
        cbTipo.setEnabled(false);
        cbVolume.setEnabled(false);
        btTipo.setEnabled(false);
        btMarca.setEnabled(false);
        int n = JOptionPane.showConfirmDialog(null,"Deseja excluir a bebida? ","Bebida",JOptionPane.YES_NO_OPTION);
        if(n==0){
            
            try{
            BebidaVO bebidaVO = new BebidaVO();
     
            int selecionada = tbTemplate.getSelectedRow();
            bebidaVO.setCodigo((int) tbTemplate.getValueAt(selecionada, 0));
            
            BebidaRN bebidaRN = new BebidaRN();
            bebidaRN.excluirBebida(bebidaVO);
           
            
            atualizarLista();
            
            //buscaBorda.popularTabela();
            
        } catch (SQLException w) {

            JOptionPane.showMessageDialog(null, "Erro: " + w.getMessage(), "Exclusão de Borda", JOptionPane.ERROR_MESSAGE);
        
        } catch (Exception w) {

            JOptionPane.showMessageDialog(null, "Erro: " + w.getMessage(), "Exclusão de Borda", JOptionPane.ERROR_MESSAGE);
        }
          JOptionPane.showMessageDialog(null,"Bebida excluida com sucesso! ","Bebida",JOptionPane.INFORMATION_MESSAGE);
    
        
        }
    }
    @Override
    public void btCancelarActionPerformed(ActionEvent e) {
        int n = JOptionPane.showConfirmDialog(null,"Deseja cancelar? ","Bebida",JOptionPane.YES_NO_OPTION);
        if(n==0){
            this.dispose();
        }
    }

    @Override
    public void btSalvarActionPerformed(ActionEvent e) {
        txtPreco.setEnabled(false);
        txtVolume.setEnabled(false);
        cbMarca.setEnabled(false);
        cbTipo.setEnabled(false);
        cbVolume.setEnabled(false);
        btTipo.setEnabled(false);
        btMarca.setEnabled(false);
        if (save == 1) {
            try{
                BebidaVO bebidaVO = new BebidaVO();

                bebidaVO.setCodigo(Integer.parseInt(txtCodigo.getText()));
                bebidaVO.setMarca((String) cbMarca.getSelectedItem());
                bebidaVO.setTipo((String) cbTipo.getSelectedItem());
                bebidaVO.setPreco(txtPreco.getText());
                bebidaVO.setVolume(Long.parseLong(txtVolume.getText()));
                bebidaVO.setUnidade((String) cbVolume.getSelectedItem());



                BebidaRN bebidaRN = new BebidaRN();
                bebidaRN.cadastrarBebida(bebidaVO);

                txtCodigo.setText("");
                txtVolume.setText("");
                txtPreco.setText("");


                atualizarLista();

                //buscaBorda.popularTabela();

                JOptionPane.showMessageDialog(null,"Bebida adicionada com sucesso! ","Bebida",JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException w) {

                JOptionPane.showMessageDialog(null, "Erro: " + w.getMessage(), "Cadastro Bebida SQL", JOptionPane.ERROR_MESSAGE);

            } catch (Exception w) {

                JOptionPane.showMessageDialog(null, "Erro: " + w.getMessage(), "Cadastro Bebida EX", JOptionPane.ERROR_MESSAGE);
            }
        } else if (save == 2) {
                try{
                BebidaVO bebidaVO = new BebidaVO();

                bebidaVO.setCodigo(Integer.parseInt(txtCodigo.getText()));
                bebidaVO.setMarca((String) cbMarca.getSelectedItem());
                bebidaVO.setTipo((String) cbTipo.getSelectedItem());
                bebidaVO.setPreco(txtPreco.getText());
                bebidaVO.setVolume(Long.parseLong(txtVolume.getText()));
                bebidaVO.setUnidade((String) cbVolume.getSelectedItem());


                BebidaRN bebidaRN = new BebidaRN();
                bebidaRN.editarBebida(bebidaVO);

                txtCodigo.setText("");
                txtVolume.setText("");
                txtPreco.setText("");

                atualizarLista();

                //buscaBorda.popularTabela();

                JOptionPane.showMessageDialog(null,"Bebida Editada com sucesso! ","Borda",JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException w) {

                JOptionPane.showMessageDialog(null, "Erro: " + w.getMessage(), "Edição de Borda", JOptionPane.ERROR_MESSAGE);

            } catch (Exception w) {

                JOptionPane.showMessageDialog(null, "Erro: " + w.getMessage(), "Edição de Borda", JOptionPane.ERROR_MESSAGE);
            }
        
        }
    }
    
    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void btMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMarcaActionPerformed
        Marca marca = new Marca();
        marca.setVisible(true);
        popularMarca();
    }//GEN-LAST:event_btMarcaActionPerformed

    private void btTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTipoActionPerformed
        TipoBebida tipo = new TipoBebida();
        tipo.setVisible(true);
    }//GEN-LAST:event_btTipoActionPerformed

    private void cbMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMarcaMouseClicked
        popularMarca();
    }//GEN-LAST:event_cbMarcaMouseClicked

    private void cbTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoMouseClicked
        popularTipo();
    }//GEN-LAST:event_cbTipoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bebida().setVisible(true);
            }
        });
    }
    
    public final void popularMarca(){
        try{
            BebidaRN bebidarn = new BebidaRN();
            ArrayList<BebidaVO> bebidas = bebidarn.popularMarca();
            
            cbMarca.removeAllItems();
            
            for (BebidaVO bebidaVO : bebidas) {
                cbMarca.addItem(bebidaVO.getMarca());
            }
        
        }catch (SQLException | ClassNotFoundException ex) {
           
        } catch (Exception ex) {
            Logger.getLogger(BebidaRN.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    public final void popularTipo(){
        try{
            BebidaRN bebidarn = new BebidaRN();
            ArrayList<BebidaVO> bebidas = bebidarn.popularTipo();
            
            cbTipo.removeAllItems();
            
            for (BebidaVO bebidaVO : bebidas) {
                cbTipo.addItem(bebidaVO.getTipo());
            }
        
        }catch (SQLException | ClassNotFoundException ex) {
           
        } catch (Exception ex) {
            Logger.getLogger(BebidaRN.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    public final void atualizarLista(){
        try{
            BebidaRN bebidarn = new BebidaRN();
            ArrayList<BebidaVO> bebidas = bebidarn.listarBebida();
            
            DefaultTableModel modelo = (DefaultTableModel)tbTemplate.getModel();
            modelo.setRowCount(0);
           
            
            for (BebidaVO bebidaVO : bebidas) {
                
                modelo.addRow(new Object[]{bebidaVO.getCodigo(),bebidaVO.getNome(),bebidaVO.getMarca(),bebidaVO.getTipo(), bebidaVO.getPreco(), bebidaVO.getUnidade(), bebidaVO.getVolume()});
            }
            tbTemplate.setModel(modelo);
            
            ajustarTabelaBorda();
            
            
    
        }catch (SQLException | ClassNotFoundException ex) {
           
        } catch (Exception ex) {
            Logger.getLogger(BebidaRN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    public final void listarBebida(){
    
        try {
            BebidaRN bebidarn = new BebidaRN();
            ArrayList<BebidaVO> bebida = bebidarn.listarBebida();
            
            DefaultTableModel modelo = (DefaultTableModel)tbTemplate.getModel();
            modelo.setRowCount(0);
           
            int n;
          
            for(n = 0; n<=6 ;n++)
                modelo.addColumn(this);
            
           
            
            for(BebidaVO bebidaVO : bebida) {
                
                modelo.addRow(new Object[]{bebidaVO.getCodigo(),bebidaVO.getNome(),bebidaVO.getMarca(),bebidaVO.getTipo(), bebidaVO.getPreco(), bebidaVO.getUnidade(), bebidaVO.getVolume()});
            }
            tbTemplate.setModel(modelo);
            
            ajustarTabelaBorda();
            
            
        } catch (SQLException | ClassNotFoundException ex) {
           
        } catch (Exception ex) {
            Logger.getLogger(BebidaRN.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ajustarTabelaBorda(){
        
        
        tbTemplate.getColumnModel().getColumn(0).setHeaderValue("Código");
        tbTemplate.getColumnModel().getColumn(1).setHeaderValue("Nome");
        tbTemplate.getColumnModel().getColumn(2).setHeaderValue("Marca");
        tbTemplate.getColumnModel().getColumn(3).setHeaderValue("Tipo");
        tbTemplate.getColumnModel().getColumn(4).setHeaderValue("Preço");
        tbTemplate.getColumnModel().getColumn(5).setHeaderValue("Unidade");
        tbTemplate.getColumnModel().getColumn(6).setHeaderValue("Volume");
        
        tbTemplate.getColumnModel().getColumn(0).setPreferredWidth(200);
        tbTemplate.getColumnModel().getColumn(1).setPreferredWidth(200);
        tbTemplate.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbTemplate.getColumnModel().getColumn(3).setPreferredWidth(200);
        tbTemplate.getColumnModel().getColumn(4).setPreferredWidth(200);
        tbTemplate.getColumnModel().getColumn(5).setPreferredWidth(100);
        tbTemplate.getColumnModel().getColumn(6).setPreferredWidth(100);
        
        tbTemplate.setDefaultEditor(Object.class, null);
        
      
    }
    private void tbTemplateMouseClicked(MouseEvent e) {                                        
        // TODO add your handling code here:
    }
        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMarca;
    private javax.swing.JButton btTipo;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> cbVolume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtVolume;
    // End of variables declaration//GEN-END:variables

    
}
