/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import regraNegocio.PedidoRN;
import vo.ConsultarClienteVO;
import vo.PedidoVO;

/**
 *
 * @author MAIKON
 */
public class Pedido extends javax.swing.JFrame {

    ArrayList<PedidoVO> listaPedidoPizza = new ArrayList();
    ArrayList<PedidoVO> listaPedidoBebida = new ArrayList();
    private Float totalPedido;
    /**
     * Creates new form TelaPedido
     */
    public Pedido() {
        initComponents();
        popularCombo();
        totalPedido = Float.valueOf(0);
        
        this.setLocationRelativeTo(null);
        setResizable(false);
    }
    public Pedido(ConsultarClienteVO cliente) {
        initComponents();
        popularCombo();
        setResizable(false);
        totalPedido = Float.valueOf(0);
        
        txtTelefone.setText(cliente.getTelefone().toString());
        txtNome.setText(cliente.getNome());
        txtCEP.setText(cliente.getCep());
        txtCidade.setText(cliente.getCidade());
        txtBairro.setText(cliente.getBairro());
        txtLogradouro.setText(cliente.getLogradouro());
        txtNumero.setText(cliente.getNumerocasa().toString());
        txtComplemento.setText(cliente.getComplemento());
        cbUF.setSelectedItem(cliente.getEstado());

        btEditar.setEnabled(true);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPedido = new javax.swing.JPanel();
        lTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        pDadosPedido = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        cbUF = new javax.swing.JComboBox<>();
        btConsultar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btAddPedido = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btCliente = new javax.swing.JButton();
        pnBebida = new javax.swing.JTabbedPane();
        pnPizzas = new javax.swing.JPanel();
        lSabor1 = new javax.swing.JLabel();
        cbSabor1 = new javax.swing.JComboBox<>();
        lTamanho = new javax.swing.JLabel();
        cbTamanho = new javax.swing.JComboBox<>();
        lSabor2 = new javax.swing.JLabel();
        cbSabor2 = new javax.swing.JComboBox<>();
        cbSabor3 = new javax.swing.JComboBox<>();
        lSabor3 = new javax.swing.JLabel();
        lBorda = new javax.swing.JLabel();
        cbBorda = new javax.swing.JComboBox<>();
        pizzasScrollPanel = new javax.swing.JScrollPane();
        tbPizza = new javax.swing.JTable();
        btAddPizza = new javax.swing.JButton();
        btRemPizza = new javax.swing.JButton();
        lTamanho1 = new javax.swing.JLabel();
        spQuant = new javax.swing.JSpinner();
        pnBebidas = new javax.swing.JPanel();
        bebidaScrollPanel = new javax.swing.JScrollPane();
        tbBebida = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        spBebida = new javax.swing.JSpinner();
        btAddBebida = new javax.swing.JButton();
        cbBebida = new javax.swing.JComboBox<>();
        btRemoveBebida = new javax.swing.JButton();
        btCancelarCli = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedido");

        lTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lTelefone.setText("Telefone do Cliente:");

        txtTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefone.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTelefoneCaretUpdate(evt);
            }
        });
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusLost(evt);
            }
        });

        pDadosPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Logradouro:");

        txtLogradouro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLogradouro.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nº");

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumero.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Complemento:");

        txtComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtComplemento.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bairro:");

        txtBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBairro.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cidade:");

        txtCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCidade.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("UF:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CEP:");

        txtCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCEP.setEnabled(false);

        cbUF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbUF.setEnabled(false);

        javax.swing.GroupLayout pDadosPedidoLayout = new javax.swing.GroupLayout(pDadosPedido);
        pDadosPedido.setLayout(pDadosPedidoLayout);
        pDadosPedidoLayout.setHorizontalGroup(
            pDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDadosPedidoLayout.createSequentialGroup()
                        .addComponent(lNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDadosPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDadosPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        pDadosPedidoLayout.setVerticalGroup(
            pDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDadosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btConsultar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultar.png"))); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.setToolTipText("Consulta os clientes cadastrado no sistema!");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("Salva aleterações realizada no cliente!");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btEditar.setText("Editar");
        btEditar.setToolTipText("Edita o cliente selecionado!");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btAddPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAddPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_add.png"))); // NOI18N
        btAddPedido.setText("Adicionar Pedido");
        btAddPedido.setToolTipText("Finaliza o pedido!");
        btAddPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPedidoActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_remove.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/users_2.png"))); // NOI18N
        btCliente.setText("Cadastrar Cliente");
        btCliente.setToolTipText("Cadastra um novo cliente de forma rápida!");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        pnBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnPizzas.setPreferredSize(new java.awt.Dimension(1289, 250));

        lSabor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSabor1.setText("Sabor 1:");

        cbSabor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSabor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma", "Quatro Queijos", "Pizza 1", "Pizza 2", "Pizza 3", "Pizza 4", "Pizza 5", "Pizza 6" }));

        lTamanho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lTamanho.setText("Tamanho:");

        cbTamanho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "P", "M", "G", "GG", " " }));

        lSabor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSabor2.setText("Sabor 2:");

        cbSabor2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSabor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma", "Quatro Queijos", "Pizza 1", "Pizza 2", "Pizza 3", "Pizza 4", "Pizza 5", "Pizza 6" }));

        cbSabor3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSabor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma", "Quatro Queijos", "Pizza 1", "Pizza 2", "Pizza 3", "Pizza 4", "Pizza 5", "Pizza 6" }));

        lSabor3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSabor3.setText("Sabor 3:");

        lBorda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lBorda.setText("Borda:");

        cbBorda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbBorda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma", "Catupiri" }));

        tbPizza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbPizza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tamanho", "Sabor 1", "Sabor 2", "Sabor 3", "Borda", "Quant.", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPizza.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPizza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbPizzaFocusGained(evt);
            }
        });
        pizzasScrollPanel.setViewportView(tbPizza);

        btAddPizza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAddPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_add.png"))); // NOI18N
        btAddPizza.setText("Adicionar Pizza");
        btAddPizza.setToolTipText("Adiciona um pizza ao pedido!");
        btAddPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPizzaActionPerformed(evt);
            }
        });

        btRemPizza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btRemPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_remove.png"))); // NOI18N
        btRemPizza.setText("Excluir Pizza");
        btRemPizza.setEnabled(false);
        btRemPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemPizzaActionPerformed(evt);
            }
        });

        lTamanho1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lTamanho1.setText("Quantidade: ");

        spQuant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spQuant.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout pnPizzasLayout = new javax.swing.GroupLayout(pnPizzas);
        pnPizzas.setLayout(pnPizzasLayout);
        pnPizzasLayout.setHorizontalGroup(
            pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPizzasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPizzasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnPizzasLayout.createSequentialGroup()
                                .addComponent(lTamanho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lBorda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbBorda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnPizzasLayout.createSequentialGroup()
                                .addComponent(lSabor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lSabor2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPizzasLayout.createSequentialGroup()
                                .addComponent(lSabor3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSabor3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnPizzasLayout.createSequentialGroup()
                                .addComponent(lTamanho1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                                .addGroup(pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btRemPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btAddPizza, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))))
                    .addComponent(pizzasScrollPanel))
                .addContainerGap())
        );
        pnPizzasLayout.setVerticalGroup(
            pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPizzasLayout.createSequentialGroup()
                .addComponent(pizzasScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSabor1)
                    .addComponent(cbSabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSabor2)
                    .addComponent(cbSabor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSabor3)
                    .addComponent(cbSabor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lTamanho)
                        .addComponent(cbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lBorda)
                        .addComponent(cbBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPizzasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAddPizza)
                        .addComponent(lTamanho1)
                        .addComponent(spQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemPizza)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnBebida.addTab("Pizzas", pnPizzas);

        tbBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bebida", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBebida.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbBebida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbBebidaFocusGained(evt);
            }
        });
        bebidaScrollPanel.setViewportView(tbBebida);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bebida :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Quantidade:");

        spBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spBebida.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btAddBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAddBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_add.png"))); // NOI18N
        btAddBebida.setText("Adicionar Bebida");
        btAddBebida.setToolTipText("Adiciona um pizza ao pedido!");
        btAddBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddBebidaActionPerformed(evt);
            }
        });

        cbBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca - Cola 2L" }));

        btRemoveBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btRemoveBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_remove.png"))); // NOI18N
        btRemoveBebida.setText("Excluir Bebida");
        btRemoveBebida.setEnabled(false);
        btRemoveBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveBebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnBebidasLayout = new javax.swing.GroupLayout(pnBebidas);
        pnBebidas.setLayout(pnBebidasLayout);
        pnBebidasLayout.setHorizontalGroup(
            pnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bebidaScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1217, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBebidasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRemoveBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAddBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnBebidasLayout.setVerticalGroup(
            pnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBebidasLayout.createSequentialGroup()
                .addComponent(bebidaScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAddBebida)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(spBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemoveBebida)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnBebida.addTab("Bebidas", pnBebidas);

        btCancelarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancelarCli.setText("Cancelar");
        btCancelarCli.setEnabled(false);
        btCancelarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarCliActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Total Pedido:");

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 51, 51));
        txtTotal.setText("R$ 0,00");

        javax.swing.GroupLayout pPedidoLayout = new javax.swing.GroupLayout(pPedido);
        pPedido.setLayout(pPedidoLayout);
        pPedidoLayout.setHorizontalGroup(
            pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDadosPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pPedidoLayout.createSequentialGroup()
                        .addComponent(lTelefone)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(pnBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pPedidoLayout.setVerticalGroup(
            pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCliente)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(pDadosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAddPedido)
                        .addComponent(btCancelar)
                        .addComponent(jLabel9)))
                .addGap(20, 20, 20))
        );

        getContentPane().add(pPedido, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        ConsultaCliente cliente = new ConsultaCliente(this);
        cliente.setVisible(true);
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Deseja alterar dados do Cliente? ","Cliente",JOptionPane.YES_NO_OPTION);
        if(n==0){
            ConsultarClienteVO cliente = new ConsultarClienteVO();
            
            cliente.setTelefone(Long.parseLong(txtTelefone.getText()));
            cliente.setNome(txtNome.getText());
            cliente.setCep(txtCEP.getText());
            cliente.setCidade(txtCidade.getText());
            cliente.setBairro(txtBairro.getText());
            cliente.setLogradouro(txtLogradouro.getText());
            cliente.setNumerocasa(Integer.parseInt(txtNumero.getText()));
            cliente.setComplemento(txtComplemento.getText());
            cliente.setEstado(cbUF.getSelectedItem().toString());
            
            PedidoRN pedidorn = new PedidoRN();
            try {
                pedidorn.alterarCliente(cliente);
            } catch (Exception ex) {
                Logger.getLogger(Pedido.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null,"Cliente alterado com sucesso! ","Cliente",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Deseja cancelar o pedido? ","Pedido",JOptionPane.YES_NO_OPTION);
        if(n==0){
            JOptionPane.showMessageDialog(null,"Pedido cancelado com sucesso! ","Pedido",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAddPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPizzaActionPerformed

        if(!"".equals(txtTelefone.getText())){
            PedidoVO pedidoGerado = new PedidoVO();
            
            if("Selecione...".equals(cbSabor1.getSelectedItem().toString()) && "Selecione...".equals(cbSabor2.getSelectedItem().toString()) && "Selecione...".equals(cbSabor3.getSelectedItem().toString())){
                JOptionPane.showMessageDialog(null,"A pizza deve conter ao menos 1 sabor !","Pedido",JOptionPane.INFORMATION_MESSAGE);

            }else if("Selecione...".equals(cbTamanho.getSelectedItem().toString())){
                JOptionPane.showMessageDialog(null,"A pizza deve conter um tamanho !","Pedido",JOptionPane.INFORMATION_MESSAGE);

            }else{
                try {
                    if("Selecione...".equals(cbSabor1.getSelectedItem().toString()))
                    pedidoGerado.setSabor1("X");
                else
                    pedidoGerado.setSabor1(cbSabor1.getSelectedItem().toString());

                if("Selecione...".equals(cbSabor2.getSelectedItem().toString()))
                    pedidoGerado.setSabor2("X");
                else
                    pedidoGerado.setSabor2(cbSabor2.getSelectedItem().toString());

                if("Selecione...".equals(cbSabor3.getSelectedItem().toString()))
                    pedidoGerado.setSabor3("X");
                else
                    pedidoGerado.setSabor3(cbSabor3.getSelectedItem().toString());

                if("Selecione...".equals(cbBorda.getSelectedItem().toString()))
                    pedidoGerado.setBorda("X");
                else
                    pedidoGerado.setBorda(cbBorda.getSelectedItem().toString());


                pedidoGerado.setQuant(Integer.parseInt(spQuant.getValue().toString()));
                pedidoGerado.setTamanho(cbTamanho.getSelectedItem().toString());

                PedidoRN pedidorn = new PedidoRN();
                PedidoVO retorno = pedidorn.valorPizza(pedidoGerado);
                pedidoGerado.setValor(retorno.getValor());

                totalPedido = totalPedido + retorno.getTotal();
                String totalTela = totalPedido.toString();
                txtTotal.setText("R$ "+totalTela.format("%.2f", totalPedido));

                listaPedidoPizza.add(pedidoGerado);

                DefaultTableModel modelo = (DefaultTableModel)tbPizza.getModel();
                modelo.setRowCount(0);
                for (PedidoVO listarTabela : listaPedidoPizza) {
                    modelo.addRow(new Object[]{listarTabela.getTamanho(), listarTabela.getSabor1(), listarTabela.getSabor2(), listarTabela.getSabor3(), listarTabela.getBorda(), listarTabela.getQuant(), listarTabela.getValor()});
                }
                tbPizza.setModel(modelo);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Erro ao inserir Pizza! ","Pedido",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }else
            JOptionPane.showMessageDialog(null,"Primeiramente selecione um cliente! ","Pedido",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btAddPizzaActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void btAddPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPedidoActionPerformed
        PedidoRN pedidorn = new PedidoRN();
        try {
            pedidorn.finalizarPedido(Long.parseLong(txtTelefone.getText()), listaPedidoBebida,listaPedidoPizza, totalPedido);
            JOptionPane.showMessageDialog(null,"Pedido cadastrado com sucesso! ","Pedido",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro ao finalizar pedido! ","Pedido",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btAddPedidoActionPerformed

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        if(!"".equals(txtTelefone.getText()))
            btEditar.setEnabled(true);
        else
            btEditar.setEnabled(false);
    }//GEN-LAST:event_txtTelefoneFocusLost

    private void btAddBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddBebidaActionPerformed
        PedidoVO pedidoGerado = new PedidoVO();
        try {
            if("Selecione...".equals(cbTamanho.getSelectedItem().toString())){
                JOptionPane.showMessageDialog(null,"Favor selecionar uma bebida!","Pedido",JOptionPane.INFORMATION_MESSAGE);
            }else{
                pedidoGerado.setQuant(Integer.parseInt(spBebida.getValue().toString()));
                pedidoGerado.setBebida(cbBebida.getSelectedItem().toString());

                PedidoRN pedidorn = new PedidoRN();
                PedidoVO retorno = pedidorn.valorBebida(pedidoGerado);
                pedidoGerado.setValor(retorno.getValor());

                totalPedido = totalPedido + retorno.getTotal();
                String totalTela = totalPedido.toString();
                txtTotal.setText("R$ "+totalTela.format("%.2f", totalPedido));

                listaPedidoBebida.add(pedidoGerado);

                DefaultTableModel modelo = (DefaultTableModel)tbBebida.getModel();
                modelo.setRowCount(0);
                for (PedidoVO listarTabela : listaPedidoBebida) {
                    modelo.addRow(new Object[]{listarTabela.getBebida(), listarTabela.getQuant(), listarTabela.getValor()});
                }
                tbBebida.setModel(modelo);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Erro ao inserir Bebida! ","Pedido",JOptionPane.INFORMATION_MESSAGE);
        }
              
        
    }//GEN-LAST:event_btAddBebidaActionPerformed

    private void btRemPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemPizzaActionPerformed
        
        int selecionada = tbPizza.getSelectedRow();
        
        try {

            DefaultTableModel modelo = (DefaultTableModel)tbPizza.getModel();
            modelo.setRowCount(0);
            for (PedidoVO listarTabela : listaPedidoPizza) {
                modelo.addRow(new Object[]{listarTabela.getTamanho(), listarTabela.getSabor1(), listarTabela.getSabor2(), listarTabela.getSabor3(), listarTabela.getBorda(), listarTabela.getQuant(),listarTabela.getValor()});
            }
            listaPedidoPizza.remove(selecionada);
           
            String valorTemporario = modelo.getValueAt(selecionada, 6).toString();
            totalPedido = totalPedido - Float.parseFloat(valorTemporario.replace(" ", "").replace("R", "").replace("$", "").replace(",", "."));
            modelo.removeRow(selecionada);
            String tratandoTotal = totalPedido.toString();
            txtTotal.setText("R$ "+tratandoTotal.format("%.2f", totalPedido));
            
            
            tbPizza.setModel(modelo); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Uma pizza deve ser selecionada!","Pedido",JOptionPane.INFORMATION_MESSAGE);
        }
        btRemPizza.setEnabled(false);
        
    }//GEN-LAST:event_btRemPizzaActionPerformed

    private void btRemoveBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveBebidaActionPerformed
        int selecionada = tbBebida.getSelectedRow();
        
        try {

            DefaultTableModel modelo = (DefaultTableModel)tbBebida.getModel();
            modelo.setRowCount(0);
            for (PedidoVO listarTabela : listaPedidoBebida) {
                modelo.addRow(new Object[]{listarTabela.getBebida(), listarTabela.getQuant(), listarTabela.getValor()});
            }
            listaPedidoBebida.remove(selecionada);
           
            String valorTemporario = modelo.getValueAt(selecionada, 2).toString();
            totalPedido = totalPedido - Float.parseFloat(valorTemporario.replace(" ", "").replace("R", "").replace("$", "").replace(",", "."));
            modelo.removeRow(selecionada);
            String tratandoTotal = totalPedido.toString();
            txtTotal.setText("R$ "+tratandoTotal.format("%.2f", totalPedido));
            
            
            tbBebida.setModel(modelo); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Uma bebida deve ser selecionada!","Pedido",JOptionPane.INFORMATION_MESSAGE);
        }
        btRemoveBebida.setEnabled(false);
        
    }//GEN-LAST:event_btRemoveBebidaActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        txtTelefone.setEnabled(false);
        txtNome.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCEP.setEnabled(true);
        txtCidade.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtNumero.setEnabled(true);
        txtLogradouro.setEnabled(true);
        cbUF.setEnabled(true);
        
        btEditar.setEnabled(false);
        btSalvar.setEnabled(true);
        btCancelarCli.setEnabled(true);
                
    }//GEN-LAST:event_btEditarActionPerformed

    private void btCancelarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarCliActionPerformed
        txtTelefone.setEnabled(true);
        txtNome.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtNumero.setEnabled(false);
        txtLogradouro.setEnabled(false);
        cbUF.setEnabled(false);
        
        btEditar.setEnabled(true);
        btSalvar.setEnabled(false);
        btCancelarCli.setEnabled(false);
    }//GEN-LAST:event_btCancelarCliActionPerformed

    private void tbPizzaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbPizzaFocusGained
        btRemPizza.setEnabled(true);
    }//GEN-LAST:event_tbPizzaFocusGained

    private void txtTelefoneCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTelefoneCaretUpdate
        try {
            Long cliente = Long.parseLong(txtTelefone.getText());
            
            PedidoRN pedidorn = new PedidoRN();
            ConsultarClienteVO clientevo = pedidorn.buscaCliente(cliente);
            
            txtTelefone.setText(clientevo.getTelefone().toString());
            txtNome.setText(clientevo.getNome());
            txtCEP.setText(clientevo.getCep());
            txtCidade.setText(clientevo.getCidade());
            txtBairro.setText(clientevo.getBairro());
            txtLogradouro.setText(clientevo.getLogradouro());
            txtNumero.setText(clientevo.getNumerocasa().toString());
            txtComplemento.setText(clientevo.getComplemento());
            cbUF.setSelectedItem(clientevo.getEstado());

            btEditar.setEnabled(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtTelefoneCaretUpdate

    private void tbBebidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbBebidaFocusGained
        btRemoveBebida.setEnabled(true);
    }//GEN-LAST:event_tbBebidaFocusGained

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }
    
    private void popularCombo() {
        try {
            PedidoRN pedidorn = new PedidoRN();
            
            cbSabor1.removeAllItems();
            cbSabor2.removeAllItems();
            cbSabor3.removeAllItems();
            cbBorda.removeAllItems();
            cbBebida.removeAllItems();
            cbUF.removeAllItems();
            
            cbSabor1.addItem("Selecione...");
            cbSabor2.addItem("Selecione...");
            cbSabor3.addItem("Selecione...");
            cbBorda.addItem("Selecione...");
            cbBebida.addItem("Selecione...");
            cbUF.addItem("Selecione...");
            
            ArrayList<ConsultarClienteVO> comboEstado = pedidorn.listarComboEstado();
            for (ConsultarClienteVO clientevo : comboEstado) {
                cbUF.addItem(clientevo.getEstado());
            }
            
            ArrayList<PedidoVO> comboSabor = pedidorn.listarComboSabor();
            for (PedidoVO pedidovo : comboSabor) {
                cbSabor1.addItem(pedidovo.getSabor());
                cbSabor2.addItem(pedidovo.getSabor());
                cbSabor3.addItem(pedidovo.getSabor());
            }
            ArrayList<PedidoVO> comboBorda = pedidorn.listarComboBorda();
            for (PedidoVO pedidovo : comboBorda) {
                cbBorda.addItem(pedidovo.getBorda());
            } 
            
            ArrayList<PedidoVO> comboBebida = pedidorn.listarComboBebida();
            for (PedidoVO pedidovo : comboBebida) {
                cbBebida.addItem(pedidovo.getBebida());
            } 
            
            
            
        } catch (SQLException | ClassNotFoundException ex) {
            
        } catch (Exception ex) {
            Logger.getLogger(Pedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Float getTotal() {
        return totalPedido;
    }

    public void setTotal(Float total) {
        this.totalPedido = total;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane bebidaScrollPanel;
    private javax.swing.JButton btAddBebida;
    private javax.swing.JButton btAddPedido;
    private javax.swing.JButton btAddPizza;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCancelarCli;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btRemPizza;
    private javax.swing.JButton btRemoveBebida;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbBebida;
    private javax.swing.JComboBox<String> cbBorda;
    private javax.swing.JComboBox<String> cbSabor1;
    private javax.swing.JComboBox<String> cbSabor2;
    private javax.swing.JComboBox<String> cbSabor3;
    private javax.swing.JComboBox<String> cbTamanho;
    private javax.swing.JComboBox<String> cbUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lBorda;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lSabor1;
    private javax.swing.JLabel lSabor2;
    private javax.swing.JLabel lSabor3;
    private javax.swing.JLabel lTamanho;
    private javax.swing.JLabel lTamanho1;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JPanel pDadosPedido;
    private javax.swing.JPanel pPedido;
    private javax.swing.JScrollPane pizzasScrollPanel;
    private javax.swing.JTabbedPane pnBebida;
    private javax.swing.JPanel pnBebidas;
    private javax.swing.JPanel pnPizzas;
    private javax.swing.JSpinner spBebida;
    private javax.swing.JSpinner spQuant;
    private javax.swing.JTable tbBebida;
    private javax.swing.JTable tbPizza;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
