/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import regraNegocio.PedidoRN;
import regraNegocio.RelogioThread;
import vo.ConsultarPedidoVO;

/**
 *
 * @author Raphael
 */
public class Principal extends javax.swing.JFrame {

    RelogioThread relogio;
    static ArrayList<ConsultarPedidoVO> pedido = new ArrayList();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        relogio = new RelogioThread(this);
        relogio.start();
        popularTabelaPrincipal();
        setResizable(false);
    }

    public void popularTabelaPrincipal() {

        try {

            PedidoRN pedidoRN = new PedidoRN();

            pedido.clear();
            pedido = pedidoRN.buscarPedido();

            DefaultTableModel modelo = (DefaultTableModel) tbPedido.getModel();

            modelo.getDataVector().clear();
            modelo.setRowCount(0);

            for (ConsultarPedidoVO pedidoVO : pedido) {

                modelo.addRow(new Object[]{
                    pedidoVO.getPedido_codigo(),
                    pedidoVO.getCliente_telefone(),
                    pedidoVO.getCliente_nome()
                });
            }
            tbPedido.setModel(modelo);

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Pedido", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbUsuario = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbData = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPedido = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btBebida = new javax.swing.JButton();
        btSabor = new javax.swing.JButton();
        btBorda = new javax.swing.JButton();
        btCliente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnSabor = new javax.swing.JMenuItem();
        mnBorda = new javax.swing.JMenuItem();
        mnBebida = new javax.swing.JMenuItem();
        mnCliente = new javax.swing.JMenuItem();
        mnPedido = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnPedidoCliente = new javax.swing.JMenuItem();
        mnPedidoPeriodo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaria Malerawa");
        setName("framePrincipal"); // NOI18N

        jPanel2.setPreferredSize(new java.awt.Dimension(857, 23));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(291, 30));

        lbUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUsuario.setText("Usuário Logado...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUsuario)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lbUsuario)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbData.setText("Data e Hora do Sistema");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbData, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lbData)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));
        jPanel6.setPreferredSize(new java.awt.Dimension(864, 380));

        tbPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pedido", "Telefone", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPedido.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPedido);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Busca :");

        txtBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });

        btCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_add.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.setToolTipText("Cadastra um novo pedido !");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/list_remove.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Exclui um pedido da tela!");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btVisualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultar.png"))); // NOI18N
        btVisualizar.setText("Visualizar");
        btVisualizar.setToolTipText("Visualiza um pedido por completo!");
        btVisualizar.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(647, 722, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btExcluir)
                    .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(855, 35));

        btBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/soft_drink.png"))); // NOI18N
        btBebida.setToolTipText("Gerencia bebidas!");
        btBebida.setIconTextGap(1);
        btBebida.setMargin(new java.awt.Insets(7, 14, 7, 14));
        btBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBebidaActionPerformed(evt);
            }
        });

        btSabor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pizza_slice.png"))); // NOI18N
        btSabor.setToolTipText("Gerencia sabores de pizza!");
        btSabor.setMargin(new java.awt.Insets(7, 14, 7, 14));
        btSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaborActionPerformed(evt);
            }
        });

        btBorda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pizza_1.png"))); // NOI18N
        btBorda.setToolTipText("Gerencia borda das pizzas!");
        btBorda.setMargin(new java.awt.Insets(7, 14, 7, 14));
        btBorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBordaActionPerformed(evt);
            }
        });

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/users_2.png"))); // NOI18N
        btCliente.setToolTipText("Gerencia os clientes !");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btBorda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBorda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSabor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jMenu1.setText("Cadastro");

        jMenu4.setText("Pizza");

        mnSabor.setText("Sabor");
        mnSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaborActionPerformed(evt);
            }
        });
        jMenu4.add(mnSabor);

        mnBorda.setText("Borda");
        mnBorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBordaActionPerformed(evt);
            }
        });
        jMenu4.add(mnBorda);

        jMenu1.add(jMenu4);

        mnBebida.setText("Bebida");
        mnBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBebidaActionPerformed(evt);
            }
        });
        jMenu1.add(mnBebida);

        mnCliente.setText("Cliente");
        mnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnCliente);

        mnPedido.setText("Pedido");
        mnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPedidoActionPerformed(evt);
            }
        });
        jMenu1.add(mnPedido);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatório");

        mnPedidoCliente.setText("Pedidos por Cliente");
        mnPedidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPedidoClienteActionPerformed(evt);
            }
        });
        jMenu2.add(mnPedidoCliente);

        mnPedidoPeriodo.setText("Pedidos por Período");
        mnPedidoPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPedidoPeriodoActionPerformed(evt);
            }
        });
        jMenu2.add(mnPedidoPeriodo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Pedido pedido = new Pedido();
        pedido.setVisible(true);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void mnSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaborActionPerformed
        Sabor sabor = new Sabor();
        sabor.setVisible(true);
    }//GEN-LAST:event_mnSaborActionPerformed

    private void mnBordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBordaActionPerformed
        Borda borda = new Borda();
        borda.setVisible(true);
    }//GEN-LAST:event_mnBordaActionPerformed

    private void mnBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBebidaActionPerformed
        Bebida bebida = new Bebida();
        bebida.setVisible(true);
    }//GEN-LAST:event_mnBebidaActionPerformed

    private void mnPedidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPedidoClienteActionPerformed
        RelatorioCliente relatorioCliente = new RelatorioCliente();
        relatorioCliente.setVisible(true);
    }//GEN-LAST:event_mnPedidoClienteActionPerformed

    private void btBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBebidaActionPerformed
        Bebida bebida = new Bebida();
        bebida.setVisible(true);
    }//GEN-LAST:event_btBebidaActionPerformed

    private void btBordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBordaActionPerformed
        Borda borda = new Borda();
        borda.setVisible(true);
    }//GEN-LAST:event_btBordaActionPerformed

    private void btSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaborActionPerformed
        Sabor sabor = new Sabor();
        sabor.setVisible(true);
    }//GEN-LAST:event_btSaborActionPerformed

    private void mnPedidoPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPedidoPeriodoActionPerformed
        RelatorioPeriodo relatorioPeriodo = new RelatorioPeriodo();
        relatorioPeriodo.setVisible(true);
    }//GEN-LAST:event_mnPedidoPeriodoActionPerformed

    private void mnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClienteActionPerformed
        Cliente cliente = new Cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_mnClienteActionPerformed

    private void mnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPedidoActionPerformed
        Pedido pedido = new Pedido();
        pedido.setVisible(true);
    }//GEN-LAST:event_mnPedidoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Deseja excluir pedido? ", "Pedido", JOptionPane.YES_NO_OPTION);
        if (n == 0) {

            try {

                int codigo;
                codigo = Integer.parseInt((String) tbPedido.getValueAt(tbPedido.getSelectedRow(), 0));

                PedidoRN pedidoRN = new PedidoRN();
                pedidoRN.excluirPedido(codigo);

                popularTabelaPrincipal();

                JOptionPane.showMessageDialog(null, "Pedido excluído com Sucesso.", "Exclusão de Pedido", JOptionPane.INFORMATION_MESSAGE);
                btCadastrar.setEnabled(true);
                btExcluir.setEnabled(false);
            } catch (SQLException sqle) {

                JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Exclusão de Pedido", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Exclusão de Pedido", JOptionPane.ERROR_MESSAGE);
            }
        }
        btCadastrar.setEnabled(true);
        btExcluir.setEnabled(false);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased

        DefaultTableModel modelo = (DefaultTableModel) tbPedido.getModel();
        modelo.setNumRows(0);

        try {
            if (txtBusca.getText().equals("")) {
                popularTabelaPrincipal();
            } else {
                PedidoRN pedidoRN = new PedidoRN();
                //pedido.clear();
                modelo.getDataVector().clear();
                pedido = (ArrayList<ConsultarPedidoVO>) pedidoRN.buscarPedidoPorNome(txtBusca.getText());
                for (ConsultarPedidoVO consultarPedidoVO : pedido) {
                    modelo.addRow(new Object[]{
                        consultarPedidoVO.getPedido_codigo(),
                        consultarPedidoVO.getCliente_telefone(),
                        consultarPedidoVO.getCliente_nome()

                    });

                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: " + ex.getMessage(), "Busca", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar cliente!\nERRO: " + ex, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtBuscaKeyReleased

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void tbPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPedidoMouseClicked

        btCadastrar.setEnabled(false);
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_tbPedidoMouseClicked

    public void setData(javax.swing.JLabel data) {
        this.lbData = data;
    }

    public javax.swing.JLabel getData() {
        return lbData;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBebida;
    private javax.swing.JButton btBorda;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSabor;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenuItem mnBebida;
    private javax.swing.JMenuItem mnBorda;
    private javax.swing.JMenuItem mnCliente;
    private javax.swing.JMenuItem mnPedido;
    private javax.swing.JMenuItem mnPedidoCliente;
    private javax.swing.JMenuItem mnPedidoPeriodo;
    private javax.swing.JMenuItem mnSabor;
    private javax.swing.JTable tbPedido;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
