/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import regraNegocio.SaborRN;
import vo.ConsultarSaborVO;

/**
 *
 * @author Maikon
 */
public class Sabor extends Template implements ActionListener {

    /**
     * Creates new form Sabor
     */
    public Sabor() {
        initComponents();
        txtCodigo.setEnabled(false);
        ajustarTabelaSabor();
        popularTabelaSabor();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    public void ajustarTabelaSabor() {

        DefaultTableModel modelo = (DefaultTableModel) tbTemplate.getModel();
        modelo.addColumn("Código");
        modelo.addColumn("Sabor");
        modelo.addColumn("Preço");
        modelo.addColumn("Tipo");
        modelo.addColumn("Status");
        modelo.addColumn("Ingredientes");

        tbTemplate.getColumnModel().getColumn(0).setPreferredWidth(70);
        tbTemplate.getColumnModel().getColumn(1).setPreferredWidth(170);
        tbTemplate.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbTemplate.getColumnModel().getColumn(3).setPreferredWidth(70);
        tbTemplate.getColumnModel().getColumn(4).setPreferredWidth(70);
        tbTemplate.getColumnModel().getColumn(5).setPreferredWidth(400);
    }

    public void popularTabelaSabor() {

        try {

            SaborRN saborRN = new SaborRN();

            ArrayList<ConsultarSaborVO> sabores = saborRN.buscarSabor();

            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tbTemplate.getModel();
            dtm.fireTableDataChanged();
            dtm.setRowCount(0);

            for (ConsultarSaborVO saborVO : sabores) {

                String[] linha = {"" + saborVO.getSab_codigo(), "" + saborVO.getSab_nome(), "R$ " + saborVO.getSab_preco(), "" + saborVO.getSab_tipo(), "" + (saborVO.isSab_status() ? "Ativo" : "Inativo"), "" + saborVO.getSab_ingredientes()};
                dtm.addRow(linha);
            }

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Sabor", JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Sabor", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSabor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngredientes = new javax.swing.JTextArea();
        pStatus = new javax.swing.JPanel();
        rbAtivo = new javax.swing.JRadioButton();
        rbInativo = new javax.swing.JRadioButton();
        pTipo = new javax.swing.JPanel();
        rbDoce = new javax.swing.JRadioButton();
        rbSalgada = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sabor");

        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Código :");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sabor :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Preço :");

        txtSabor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSabor.setToolTipText("");
        txtSabor.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ingredientes:");

        txtIngredientes.setColumns(20);
        txtIngredientes.setRows(5);
        txtIngredientes.setEnabled(false);
        jScrollPane1.setViewportView(txtIngredientes);

        pStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbAtivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbAtivo.setSelected(true);
        rbAtivo.setText("Ativo");
        rbAtivo.setEnabled(false);
        rbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAtivoActionPerformed(evt);
            }
        });

        rbInativo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbInativo.setText("Inativo");
        rbInativo.setEnabled(false);
        rbInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbInativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pStatusLayout = new javax.swing.GroupLayout(pStatus);
        pStatus.setLayout(pStatusLayout);
        pStatusLayout.setHorizontalGroup(
            pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStatusLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbInativo)
                    .addComponent(rbAtivo))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        pStatusLayout.setVerticalGroup(
            pStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAtivo)
                .addGap(18, 18, 18)
                .addComponent(rbInativo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pTipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbDoce.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbDoce.setSelected(true);
        rbDoce.setText("Doce");
        rbDoce.setEnabled(false);
        rbDoce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDoceActionPerformed(evt);
            }
        });

        rbSalgada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSalgada.setText("Salgada");
        rbSalgada.setEnabled(false);
        rbSalgada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSalgadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pTipoLayout = new javax.swing.GroupLayout(pTipo);
        pTipo.setLayout(pTipoLayout);
        pTipoLayout.setHorizontalGroup(
            pTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTipoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSalgada)
                    .addComponent(rbDoce))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        pTipoLayout.setVerticalGroup(
            pTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbDoce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(rbSalgada)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tipo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Status:");

        txtPreco.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(pTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtSabor))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbDoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDoceActionPerformed
        rbDoce.setSelected(true);
        rbSalgada.setSelected(false);
    }//GEN-LAST:event_rbDoceActionPerformed

    private void rbSalgadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSalgadaActionPerformed
        rbDoce.setSelected(false);
        rbSalgada.setSelected(true);
    }//GEN-LAST:event_rbSalgadaActionPerformed

    private void rbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAtivoActionPerformed
        rbAtivo.setSelected(true);
        rbInativo.setSelected(false);
    }//GEN-LAST:event_rbAtivoActionPerformed

    private void rbInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbInativoActionPerformed
        rbAtivo.setSelected(false);
        rbInativo.setSelected(true);
    }//GEN-LAST:event_rbInativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sabor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sabor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sabor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sabor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sabor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pStatus;
    private javax.swing.JPanel pTipo;
    private javax.swing.JRadioButton rbAtivo;
    private javax.swing.JRadioButton rbDoce;
    private javax.swing.JRadioButton rbInativo;
    private javax.swing.JRadioButton rbSalgada;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtIngredientes;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JTextField txtSabor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void btCadastrarActionPerformed(ActionEvent e) {
        txtIngredientes.setEnabled(true);
        txtPreco.setEnabled(true);
        txtSabor.setEnabled(true);
        rbDoce.setEnabled(true);
        rbSalgada.setEnabled(true);
        rbAtivo.setEnabled(true);
        rbInativo.setEnabled(true);

        SaborRN saborRN = new SaborRN();
        try {
            int ultimoID = saborRN.pegarUltimoID() + 1;
            txtCodigo.setText(String.valueOf(ultimoID));
        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Sabor", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Sabor", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void btEditarActionPerformed(ActionEvent e) {
        txtIngredientes.setEnabled(true);
        txtPreco.setEnabled(true);
        txtSabor.setEnabled(true);
        rbDoce.setEnabled(true);
        rbSalgada.setEnabled(true);
        rbAtivo.setEnabled(true);
        rbInativo.setEnabled(true);

        String valorTemporario = ((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 2));

        txtCodigo.setText((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 0));
        txtSabor.setText((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 1));
        txtPreco.setText(valorTemporario.replace(" ", "").replace("R", "").replace("$", "").replace(",", "."));

        if ("Doce".equals(tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 3))) {
            rbDoce.setSelected(true);
            rbSalgada.setSelected(false);
        } else {
            rbSalgada.setSelected(true);
            rbDoce.setSelected(false);
        }

        if ("Ativo".equals((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 4))) {
            rbAtivo.setSelected(true);
            rbInativo.setSelected(false);
        } else {
            rbInativo.setSelected(true);
            rbAtivo.setSelected(false);
        }

        txtIngredientes.setText((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 5));
    }

    @Override
    public void btExcluirActionPerformed(ActionEvent e) {
        txtIngredientes.setEnabled(false);
        txtPreco.setEnabled(false);
        txtSabor.setEnabled(false);
        rbDoce.setEnabled(false);
        rbSalgada.setEnabled(false);

        int n = JOptionPane.showConfirmDialog(null, "Deseja excluir o sabor de pizza? ", "Sabor", JOptionPane.YES_NO_OPTION);
        if (n == 0) {

            try {

                int codigo;
                codigo = Integer.parseInt((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 0));

                SaborRN saborRN = new SaborRN();
                saborRN.excluirSabor(codigo);

                popularTabelaSabor();

                JOptionPane.showMessageDialog(null, "Sabor excluído com Sucesso.", "Exclusão de Sabor", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException sqle) {

                JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Exclusão de Sabor", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Exclusão de Sabor", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    @Override
    public void btCancelarActionPerformed(ActionEvent e) {
        int n = JOptionPane.showConfirmDialog(null, "Deseja cancelar? ", "Sabor", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            this.dispose();
        }
    }

    @Override
    public void btSalvarActionPerformed(ActionEvent e) {
        txtIngredientes.setEnabled(false);
        txtPreco.setEnabled(false);
        txtSabor.setEnabled(false);
        rbDoce.setEnabled(false);
        rbSalgada.setEnabled(false);
        rbAtivo.setEnabled(false);
        rbInativo.setEnabled(false);

        if (save == 1) {

            try {

                ConsultarSaborVO saborVO = new ConsultarSaborVO();

                saborVO.setSab_nome(txtSabor.getText());
                saborVO.setSab_preco(Float.parseFloat(txtPreco.getText()));
                saborVO.setSab_tipo(rbDoce.isSelected() ? "Doce" : "Salgado");
                saborVO.setSab_status(rbAtivo.isSelected());
                saborVO.setSab_ingredientes(txtIngredientes.getText());

                SaborRN saborRN = new SaborRN();
                saborRN.cadastrarSabor(saborVO);

                popularTabelaSabor();

                JOptionPane.showMessageDialog(null, "Sabor Cadastrado com Sucesso.", "Cadastro de Sabor", JOptionPane.INFORMATION_MESSAGE);

                txtCodigo.setText("");
                txtIngredientes.setText("");
                txtPreco.setText("");
                txtSabor.setText("");

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Cadastro de Sabor", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Cadastro de Sabor", JOptionPane.ERROR_MESSAGE);
            }

        } else if (save == 2) {

            try {

                ConsultarSaborVO saborVO = new ConsultarSaborVO();

                saborVO.setSab_codigo(Integer.parseInt((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 0)));
                saborVO.setSab_nome(txtSabor.getText());
                saborVO.setSab_preco(Float.parseFloat(txtPreco.getText()));
                saborVO.setSab_tipo(rbDoce.isSelected() ? "Doce" : "Salgado");
                saborVO.setSab_status(rbAtivo.isSelected());
                saborVO.setSab_ingredientes(txtIngredientes.getText());

                SaborRN saborRN = new SaborRN();
                saborRN.atualizarSabor(saborVO);

                popularTabelaSabor();

                JOptionPane.showMessageDialog(null, "Sabor de Pizza Atualizado com Sucesso.", "Edição Sabor de Pizza", JOptionPane.INFORMATION_MESSAGE);

                txtCodigo.setEnabled(false);
                txtCodigo.setText("");
                txtIngredientes.setEditable(false);
                txtIngredientes.setText("");
                txtPreco.setEnabled(false);
                txtPreco.setText("");
                txtSabor.setEnabled(false);
                txtSabor.setText("");
                rbAtivo.setSelected(true);
                rbInativo.setSelected(false);
                rbDoce.setSelected(true);
                rbSalgada.setSelected(false);

                btCancelar.setEnabled(true);

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Edição Sabor de Pizza", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Edição Sabor de Pizza", JOptionPane.ERROR_MESSAGE);
            }
        }

    }
}
