/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import regraNegocio.TipoBebidaRN;
import vo.TipoBebidaVO;

/**
 *
 * @author Raphael
 */
public class TipoBebida extends Template implements ActionListener {

    /**
     * Creates new form TipoBebida
     */
    public TipoBebida() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ajustarTabelaTipoBebida();
        popularTabela();
    }

    public void ajustarTabelaTipoBebida() {

        DefaultTableModel modelo = (DefaultTableModel) tbTemplate.getModel();
        modelo.addColumn("Código");
        modelo.addColumn("Tipo de Bebida");
        tbTemplate.getColumnModel().getColumn(0).setPreferredWidth(100);
        tbTemplate.getColumnModel().getColumn(1).setPreferredWidth(492);
    }

    public void popularTabela() {

        try {

            TipoBebidaRN tipoBebidaRN = new TipoBebidaRN();

            ArrayList<TipoBebidaVO> tipoBebida = tipoBebidaRN.buscarTiposBebidas();

            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tbTemplate.getModel();
            dtm.fireTableDataChanged();
            dtm.setRowCount(0);

            for (TipoBebidaVO tipoBebidaVO : tipoBebida) {

                String[] linha = {"" + tipoBebidaVO.getBebtip_codigo(), "" + tipoBebidaVO.getBebtip_nome()};
                dtm.addRow(linha);
            }

        } catch (SQLException sqle) {

            JOptionPane.showMessageDialog(null, "Erro: " + sqle.getMessage(), "Tipo de Bebidas", JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage(), "Tipo de Bebidas", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipos de Bebidas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tipo Bebida :");

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTipo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoBebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void btCadastrarActionPerformed(ActionEvent e) {
        txtTipo.setEnabled(true);
    }

    private void tbTemplateMouseClicked(java.awt.event.MouseEvent evt) {
        btCadastrar.setEnabled(false);
        btEditar.setEnabled(true);
        btCancelar.setEnabled(true);
    }

    @Override
    public void btEditarActionPerformed(ActionEvent e) {
        txtTipo.setEnabled(true);
        txtTipo.setText((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 1));

        TipoBebidaVO tipoBebidaVO = new TipoBebidaVO();

        tipoBebidaVO.setBebtip_codigo(Integer.parseInt((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 0)));
        tipoBebidaVO.setBebtip_nome(txtTipo.getText());

    }

    @Override
    public void btExcluirActionPerformed(ActionEvent e) {
        txtTipo.setEnabled(false);

        int n = JOptionPane.showConfirmDialog(null, "Deseja excluir um tipo de bebida? ", "Tipo de Bebida", JOptionPane.YES_NO_OPTION);
        if (n == 0) {

            try {

                TipoBebidaVO tipoBebidaVO = new TipoBebidaVO();

                tipoBebidaVO.setBebtip_codigo(Integer.parseInt((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 0)));
                tipoBebidaVO.setBebtip_nome((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 1));

                TipoBebidaRN tipoBebidaRN = new TipoBebidaRN();
                tipoBebidaRN.excluirTipoBebida(tipoBebidaVO);

                popularTabela();

                JOptionPane.showMessageDialog(null, "Registro excluído com Sucesso.", "Exclusão Tipo de Bebida", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException sqle) {

                JOptionPane.showMessageDialog(null, "Erro: Este tipo de bebida não pode ser excluída, pois possui dados associados! ", "Exclusão de Bebida", JOptionPane.ERROR_MESSAGE);

            } catch (ArrayIndexOutOfBoundsException aiobe) {

                JOptionPane.showMessageDialog(null, "Selecione um aluno.", "Exclusão Tipo de Bebida", JOptionPane.WARNING_MESSAGE);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Exclusão Tipo de Bebida", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    @Override
    public void btCancelarActionPerformed(ActionEvent e) {
        int n = JOptionPane.showConfirmDialog(null, "Deseja cancelar? ", "Tipo de Bebida", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            this.dispose();
        }
    }

    @Override
    public void btSalvarActionPerformed(ActionEvent e) {
        txtTipo.setEnabled(false);

        if (save == 1) {

            try {

                TipoBebidaVO tipoBebidaVO = new TipoBebidaVO();

                tipoBebidaVO.setBebtip_nome(txtTipo.getText());

                TipoBebidaRN tipoBebidaRN = new TipoBebidaRN();
                tipoBebidaRN.cadastrarTipoBebida(tipoBebidaVO);

                popularTabela();

                JOptionPane.showMessageDialog(null, "Tipo de bebida Cadastrado com Sucesso.", "Cadastro Tipo de bebida", JOptionPane.INFORMATION_MESSAGE);
                txtTipo.setText("");
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Cadastro Tipo de bebida", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Cadastro Tipo de bebida", JOptionPane.ERROR_MESSAGE);
            }

        } else if (save == 2) {

            try {

                TipoBebidaVO tipoBebidaVO = new TipoBebidaVO();

                tipoBebidaVO.setBebtip_codigo(Integer.parseInt((String) tbTemplate.getValueAt(tbTemplate.getSelectedRow(), 0)));
                tipoBebidaVO.setBebtip_nome(txtTipo.getText());

                TipoBebidaRN tipoBebidaRN = new TipoBebidaRN();
                tipoBebidaRN.editarTipoBebida(tipoBebidaVO);

                popularTabela();

                JOptionPane.showMessageDialog(null, "Tipo de bebida Atualizado com Sucesso.", "Edição Tipo de bebida", JOptionPane.INFORMATION_MESSAGE);

                txtTipo.setText("");
                txtTipo.setEnabled(true);
                btCancelar.setEnabled(true);

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Edição Tipo de bebida", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage(), "Edição Tipo de bebida", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
